replicaCount: 1
image:
  repository: ghcr.io/fitnest-backend/fitmarket-service
  tag: "latest"
  pullPolicy: IfNotPresent
  imagePullSecrets:
    - name: ghcr-secret
service:
  type: ClusterIP
  port: 8080
istio:
  enabled: true
  host: "fitmarket-service"
env:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresql-fitmarket:5432/fitnest_fitmarket"
  SPRING_DATASOURCE_USERNAME: "fitnest_fitmarket"
  SPRING_DATASOURCE_PASSWORD: "fitmarket_password_123"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
